# Generated by Django 5.1 on 2024-08-21 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_of_publish', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demands_standard_computer_software', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('firm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('description', models.TextField()),
                ('firm', models.CharField(max_length=255)),
                ('date_of_creation', models.DateField()),
                ('date_of_sale', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_creation', models.IntegerField()),
                ('date_of_sell', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('firm', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parts', models.ManyToManyField(related_name='computers', to='myapp.part')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('computers', models.ManyToManyField(blank=True, related_name='carts', to='myapp.computer')),
                ('games', models.ManyToManyField(blank=True, related_name='carts', to='myapp.game')),
                ('parts', models.ManyToManyField(blank=True, related_name='carts', to='myapp.part')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carts', models.ManyToManyField(related_name='shops', to='myapp.cart')),
                ('computers', models.ManyToManyField(related_name='shops', to='myapp.computer')),
                ('games', models.ManyToManyField(related_name='shops', to='myapp.game')),
                ('parts', models.ManyToManyField(related_name='shops', to='myapp.part')),
                ('users', models.ManyToManyField(related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
